### ISSUE TITLE
presencelight-worker in docker-container (Raspi4)

### ISSUE THREAD

**Issue by Chris76FiSi** [isaacrlevin/presencelight#237]
First, i can only access presencelight through exposed ports 5000 and 5001 from Raspi itself with URL https://127.0.0.1:5001. From network i can not access ist. netstat outside of container is showing:
tcp        0      0 127.0.0.1:5000          0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:5001          0.0.0.0:*               LISTEN

To access the presencelight-worker in docker container i installed chromium-browser on the Raspi. After login with my credentials presencelight is getting my Teams state - perfect. But when i close the browser presencelight-worker looses the authentication. Attached you will find a log from docker container. Do you have an idea what's going wrong?

Thanks a lot for your work on this project. *thumbsup*
[_presencelight_logs.txt](https://github.com/isaacrlevin/presencelight/files/5863194/_presencelight_logs.txt)

**Comment by isaacrlevin** [comment]
I am aware of this. I am working with the Microsoft.Identity.UI team to resolve.

As for your port mapping. What does your docker-compose.yaml look like? Also are you using my cert or supplying your own. Also might be good to submit an issue using the template

**Comment by Chris76FiSi** [comment]
Thanks for your reply.
I tried different .yml configurations. 
With [presencelight_1.yml.txt](https://github.com/isaacrlevin/presencelight/files/5873176/presencelight_1.yml.txt) i have the following ports opened on the docker host:

tcp        0      0 0.0.0.0:4433            0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:7999            0.0.0.0:*               LISTEN

But when i try to connect with my browser (Google Chrome or Edge Chromium) i get ERR_CONNECTION_REFUSED - both through port 7999 with http or 4433 with https.

With [presencelight_2.yml.txt](https://github.com/isaacrlevin/presencelight/files/5873208/presencelight_2.yml.txt) - container is connected to network host - i can access presencelight within RPi through http://127.0.0.1:5000 or https://172.0.0.1:5001 but not from outside of RPi, e.g. from my Windows machine. The following ports are opened on RPi:
tcp        0      0 127.0.0.1:5000          0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:5001          0.0.0.0:*               LISTEN

Hope this will help. Thanks in advance.

**Comment by isaacrlevin** [comment]
Sadly what you are trying to do is not going to work. Look at the information here
![image](https://user-images.githubusercontent.com/8878502/105879675-51258780-5fb7-11eb-996a-efd84fc7b722.png)

You need to be running PresenceLight as one of the above urls **From the system you are going to access it**. This means that if you want to access it over the network, it has to be `192.168.86.27:4433` because that is what AAD registers

**Comment by Chris76FiSi** [comment]
Thanks for you reply. I hope you can fix the browser close issue with Microsoft.Identity.UI team.

**Comment by isaacrlevin** [comment]
Are you able to map your web address to the IP I provided?

**Comment by Chris76FiSi** [comment]
I configured a docker network and attached the presencelight container to it so the container got the ip 192.168.86.27. I can ping the conainer but cannot open the URL https://192.168.86.27:4433
Maybe I missunderstood the setup you mean but i don't want you to waste your time. Thanks.

**Comment by isaacrlevin** [comment]
Sorry you are having issues, here is the docker-compose I run (it runs on a Rasperry Pi 4b RGM RAM , use the latest tag for non-ARM)

```yml
version: '3.7'

services:
  presencelight:
    image: isaaclevin/presencelight:debian-arm32
    container_name: presencelight
    restart: unless-stopped
    environment:
      TZ: "America/Los_Angeles"
      ASPNETCORE_ENVIRONMENT: "Development"
      AzureAd__ClientId: ""
      AzureAd__ClientSecret: ""
      ApplicationInsights__InstrumentationKey: ""
      ASPNETCORE_URLS: "https://+:443;http://+:80"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "password"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/presencelight.pfx"
    ports:
      - "8003:80"
      - "4433:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.aspnet/https:/https:ro This is how I do the cert in my case. I self sign using dotnet global tool
```
