### ISSUE TITLE
Run Without SSL Cert?

### ISSUE THREAD

**Issue by mikefarwell** [isaacrlevin/presencelight#369]
I'm also using Traefik in my setup and so don't need an SSL cert as Traefik is handling all that. Do you have any instructions on how to run the Docker image without creating a dev cert?

For reference, I'm intending to access the site at presencelight.redacted.com, but presencelight.local would be acceptable as well, so I have both set up for now. I'm running in a docker swarm and my stack is below:
```
version: '3.3'
services:
  presencelight:
    image: isaaclevin/presencelight:debian-arm64
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+:5001;http://+:5000
      AzureAd__RedirectHost: https://presencelight.local/signin-oidc
      TZ: America/Chicago
    volumes:
      - /dockervolumes/presencelight:/app/config
    networks:
      - web_public
    logging:
      driver: json-file
    deploy:
      labels:
        traefik.docker.network: web_public
        traefik.enable: 'true'
        traefik.http.routers.presencelight.entrypoints: https
        traefik.http.routers.presencelight.rule: Host(presencelight.redacted.com, presencelight.local)
        traefik.http.routers.presencelight.service: presencelight
        traefik.http.services.presencelight.loadbalancer.server.port: '5000'
networks:
  web_public:
    external: true
```
