### ISSUE TITLE
Docker: appsettings.json settings are not overwritten

### ISSUE THREAD

**Issue by martinhoess** [isaacrlevin/presencelight#963]
**Describe the bug**

According to [this comment](https://github.com/isaacrlevin/presencelight/issues/325#issuecomment-803191234), the RedirectHost setting is overridden in the appsettings.json ... but that doesn’t seem to be correct.

I had the issue where the redirect ended up in a loop, and it kept trying multiple times but couldn’t log in. 

`ResponseBody: {"error":"invalid_client","error_description":"AADSTS500112: The reply address 'https://localhost:5001/signin-oidc' does not match the reply address 'https://presencelight.local:4433/signin-oidc' provided when requesting Authorization code. Trace ID: XXXX Correlation ID: XXXX Timestamp: 2025-01-06 16:50:28Z","error_codes":[500112],"timestamp":"2025-01-06 16:50:28Z","trace_id":"XXX","correlation_id":"XXX"}`

I then manually altered the appsettings.json to match the settings in the docker compose, and after the restart, the login/redirect worked.

`"RedirectHost": "https://presencelight.local:4433",`

**To Reproduce**
```
services:
  presencelight:
    image: isaaclevin/presencelight:latest
    container_name: presencelight
    restart: unless-stopped
    ports:
      - 8008:80
      - 4433:443
    volumes:
      - /volume1/docker/presencelight/https:/https:ro
      - /volume1/docker/presencelight/config:/app/config
      - /volume1/docker/presencelight/aspnet:/root/.aspnet
    networks:
      - presencelight_default
    hostname: presencelight
    environment:
      ASPNETCORE_HTTPS_PORT: "4433"
      ASPNETCORE_URLS: "https://+:443;http://+:80"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "test"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/presencelight.pfx"
      AzureAd__RedirectHost: "https://presencelight.local:4433/signin-oidc"
      ASPNETCORE_ENVIRONMENT: "Development"
      Serilog__MinimumLevel: "Error"

networks: 
    presencelight_default:
        external: true
```

**Expected behavior**
Login without needing to adjust the appconfig.

**Screenshots**
![image](https://github.com/user-attachments/assets/6eca9f05-7a09-43d9-ab26-243ae3f99ffb)
![image](https://github.com/user-attachments/assets/de90a293-942b-44f0-9c99-151d94eca925)

## Further details
- Synology docker environment
