### ISSUE TITLE
Docker: Invalid Client Secret Provided

### ISSUE THREAD

**Issue by churchs19** [isaacrlevin/presencelight#966]
**Describe the bug**
I am getting the error:

```
Microsoft.Identity.Client.MsalServiceException: A configuration issue is preventing authentication - check the error message from the server for details. You can modify the configuration in the application registration portal. See https://aka.ms/msal-net-invalid-client for details.  Original exception: AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app 'f8119f58-4523-44c1-ab72-b2e0c815bd6a'. Trace ID: 0cb43741-41e0-42d3-b098-96ae3e951300 Correlation ID: c1062dbc-1d11-49f6-856a-3e55b30eea6b Timestamp: 2025-02-03 17:29:48Z
```

I've been running Presence Light through Docker for a long time on Mac and this was working as recently as last Friday. When I signed back in for work today, this is the error I got. I tried deleting the Docker container and restarting from scratch using the Docker instructions here and got the same error.

**To Reproduce**

- Install the Docker container with the steps in the [web readmer](https://github.com/isaacrlevin/presencelight/blob/main/docs/web-README.md). 
- Run `docker-compose up`
- See the error

**Expected behavior**
App authenticates successfully

**Screenshots**
Docker-compose.yml

```yml
services:
  presencelight:
    image: isaaclevin/presencelight:debian-arm64
    container_name: presencelight
    restart: unless-stopped
    environment:
      TZ: "America/Chicago"
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "https://+:5001;http://+:5000"
      AzureAd__RedirectHost: "https://localhost:5001"
      Kestrel__Certificates__Default__Path: "https/presencelight.pfx"
      Kestrel__Certificates__Default__Password: "presencelight"
    ports:
      - "8003:5000"
      - "5001:5001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users/schurch/presencelight/https:/app/https:rw
      - /Users/schurch/presencelight/config:/app/config:rw
      - /Users/schurch/presencelight/aspnet:/root/.aspnet:rw
```

## Further details
- OS: Mac OS 15.2
- PresenceLight App Type: Docker
- PresenceLight Build: Docker image `isaaclevin/presencelight:debian-arm64`
